app/models/datatest.py
from flask import current_app
from flask_login import AnonymousUserMixin, UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import BadSignature, SignatureExpired
from werkzeug.security import check_password_hash, generate_password_hash

from .. import db, login_manager

class Datatest(db.Model):
    __tablename__ = 'datatest'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    d1 = db.Column(db.String(64))
    d2 = db.Column(db.String(64))
    d3 = db.Column(db.DateTime)
    d4 = db.Column(db.Float)
    # users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return '<Datatest \'%s\'>' % self.name

app/admin/datatest/forms.py
from flask_wtf import FlaskForm
from wtforms import ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.fields import (
    StringField,
    SubmitField,
)
from wtforms.validators import (
    Email,
    EqualTo,
    InputRequired,
    Length,
)

from app import db
from app.models import datatest

class DatatestForm(FlaskForm):

    name = StringField('Name', validators=[InputRequired(), Length(1, 64)])
    d1 = StringField('d1', validators=[InputRequired(), Length(1, 64)])
    d2 = StringField('d2', validators=[InputRequired(), Length(1, 64)])
    d3 = StringField('d3', validators=[InputRequired(), Length(1, 64)])
    d4 = StringField('d4', validators=[InputRequired(), Length(1, 64)])

    submit = SubmitField('Submit')

app/admin/datatest/__init__.py
from app.admin.datatest.views import datatest  # noqa

app/admin/datatest/views.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.admin.datatest.forms import (
    DatatestForm,
)
from app.decorators import admin_required
from app.email import send_email
from app.models import Datatest
import json
datatest = Blueprint('datatest', __name__)
from app.repositories.DatatestRepository import DatatestRepository
dataRepo = DatatestRepository(db)

@datatest.route('/')
@login_required
@admin_required
def index():
    """Admin dashboard page."""
    datas = dataRepo.all()
    return render_template('master/datatest/index.html', datas=datas)


@datatest.route('/create', methods=['GET', 'POST'])
@login_required
@admin_required
def create():
    """Create a new data."""
    form = DatatestForm()
    if form.validate_on_submit():
        dataRepo.setFormData(form).insert()
        flash('Datatest {} successfully created'.format(dataRepo.lastData.name), 'form-success')
        return redirect(url_for('datatest.index'))
    return render_template('master/datatest/add-edit.html', form=form)


@datatest.route('/datatest')
@login_required
@admin_required
def all():
    """View all registered datatests."""
    datatests = Datatest.query.all()
    return render_template(
        'master/datatest/index.html', datatests=datatests, roles=roles)


@datatest.route('/edit/<int:id>', methods = ['GET', 'POST'])
# @datatest.route('/datatest/<int:id>/info')
@login_required
@admin_required
def edit(id):
    """edit datatest"""
    
    dbdata = dataRepo.single(id)
    form = DatatestForm(obj=dbdata)
    if dbdata is None:
        abort(404)

    if request.method == 'POST':
        form = DatatestForm()
        if form.validate_on_submit():
            dataRepo.setId(id).setFormData(form, 'update').update()
            flash('Data successfully changed to {}.'.format(dataRepo.lastData.name, 'form-success'))
            return redirect(url_for('datatest.edit', id=id))
    else:
        return render_template('master/datatest/add-edit.html', 
            data=dbdata, 
            form=form)
    


@datatest.route('/_delete/<int:id>/')
@login_required
@admin_required
def delete(id):
    """Delete data."""
    data = dataRepo.delete(id)
    flash('Successfully deleted data %s.' % data.name, 'success')

    return redirect(url_for('datatest.index'))

app/admin/views.py
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from flask_rq import get_queue

from app import db
from app.admin.forms import (
    ChangeAccountTypeForm,
    ChangeUserEmailForm,
    InviteUserForm,
    NewUserForm,
)
from app.decorators import admin_required
from app.email import send_email
from app.models import EditableHTML, Role, User

admin = Blueprint('admin', __name__)


@admin.route('/')
@login_required
@admin_required
def index():
    """Admin dashboard page."""
    return render_template('admin/index.html')


@admin.route('/new-user', methods=['GET', 'POST'])
@login_required
@admin_required
def new_user():
    """Create a new user."""
    form = NewUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('User {} successfully created'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/invite-user', methods=['GET', 'POST'])
@login_required
@admin_required
def invite_user():
    """Invites a new user to create an account and set their own password."""
    form = InviteUserForm()
    if form.validate_on_submit():
        user = User(
            role=form.role.data,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        invite_link = url_for(
            'account.join_from_invite',
            user_id=user.id,
            token=token,
            _external=True)
        get_queue().enqueue(
            send_email,
            recipient=user.email,
            subject='You Are Invited To Join',
            template='account/email/invite',
            user=user,
            invite_link=invite_link,
        )
        flash('User {} successfully invited'.format(user.full_name()),
              'form-success')
    return render_template('admin/new_user.html', form=form)


@admin.route('/users')
@login_required
@admin_required
def registered_users():
    """View all registered users."""
    users = User.query.all()
    roles = Role.query.all()
    return render_template(
        'admin/registered_users.html', users=users, roles=roles)


@admin.route('/user/<int:user_id>')
@admin.route('/user/<int:user_id>/info')
@login_required
@admin_required
def user_info(user_id):
    """View a user's profile."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/change-email', methods=['GET', 'POST'])
@login_required
@admin_required
def change_user_email(user_id):
    """Change a user's email."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    form = ChangeUserEmailForm()
    if form.validate_on_submit():
        user.email = form.email.data
        db.session.add(user)
        db.session.commit()
        flash('Email for user {} successfully changed to {}.'.format(
            user.full_name(), user.email), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route(
    '/user/<int:user_id>/change-account-type', methods=['GET', 'POST'])
@login_required
@admin_required
def change_account_type(user_id):
    """Change a user's account type."""
    if current_user.id == user_id:
        flash('You cannot change the type of your own account. Please ask '
              'another administrator to do this.', 'error')
        return redirect(url_for('admin.user_info', user_id=user_id))

    user = User.query.get(user_id)
    if user is None:
        abort(404)
    form = ChangeAccountTypeForm()
    if form.validate_on_submit():
        user.role = form.role.data
        db.session.add(user)
        db.session.commit()
        flash('Role for user {} successfully changed to {}.'.format(
            user.full_name(), user.role.name), 'form-success')
    return render_template('admin/manage_user.html', user=user, form=form)


@admin.route('/user/<int:user_id>/delete')
@login_required
@admin_required
def delete_user_request(user_id):
    """Request deletion of a user's account."""
    user = User.query.filter_by(id=user_id).first()
    if user is None:
        abort(404)
    return render_template('admin/manage_user.html', user=user)


@admin.route('/user/<int:user_id>/_delete')
@login_required
@admin_required
def delete_user(user_id):
    """Delete a user's account."""
    if current_user.id == user_id:
        flash('You cannot delete your own account. Please ask another '
              'administrator to do this.', 'error')
    else:
        user = User.query.filter_by(id=user_id).first()
        db.session.delete(user)
        db.session.commit()
        flash('Successfully deleted user %s.' % user.full_name(), 'success')
    return redirect(url_for('admin.registered_users'))


@admin.route('/_update_editor_contents', methods=['POST'])
@login_required
@admin_required
def update_editor_contents():
    """Update the contents of an editor."""

    edit_data = request.form.get('edit_data')
    editor_name = request.form.get('editor_name')

    editor_contents = EditableHTML.query.filter_by(
        editor_name=editor_name).first()
    if editor_contents is None:
        editor_contents = EditableHTML(editor_name=editor_name)
    editor_contents.value = edit_data

    db.session.add(editor_contents)
    db.session.commit()

    return 'OK', 200

app/templates/master/datatest/add-edit.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('datatest.index') }}">
                <i class="caret left icon"></i>
                Back
            </a>
            <h2 class="ui header">
                <!-- to do : conditional title -->
                Add New Data
                <div class="sub header">Create a new data</div>
            </h2>
            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                <div class="two fields">
                    {{ f.render_form_field(form.name) }}
                    {{ f.render_form_field(form.d1) }}
                </div>

                {{ f.render_form_field(form.d2) }}
                {{ f.render_form_field(form.d3) }}
                {{ f.render_form_field(form.d4) }}

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                    {{ f.render_form_field(field) }}
                {% endfor %}

            {{ f.end_form() }}
            {% if form.password %} 
              {{ check.password_check('password', 0) }} 
            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/master/datatest/index.html
{% extends 'layouts/base.html' %}

{% import 'macros/button_macros.html' as btnMacro %}

{% block content %}
    <div class="ui stackable grid container">
        <div class="sixteen wide tablet twelve wide computer centered column">
            <a class="ui basic compact button" href="{{ url_for('admin.index') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <a class="ui basic compact button" href="{{ url_for('datatest.create') }}">
                <i class="caret plus icon"></i>
                +Add
            </a>

            <div class="ui menu">
                <div id="select-role" class="ui dropdown item">
                    <div class="text">
                        All account types
                    </div>
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <div class="item" data-value="">All account types</div>
                        {% for r in roles %}
                            <div class="item" data-value="{{ r.name }}">{{ r.name }}s</div>
                        {% endfor %}
                    </div>
                </div>
                <div class="ui right search item">
                    <div class="ui transparent icon input">
                        <input id="search-users" type="text" placeholder="Search users…">
                        <i class="search icon"></i>
                    </div>
                </div>
            </div>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>name</th>
                            <th>d1</th>
                            <th>d2</th>
                            <th>d3</th>
                            <th>d4</th>
                            <th>action</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for d in datas %}
                        <tr>
                            <td>{{ d.id }}</td>
                            <td>{{ d.name }}</td>
                            <td>{{ d.d1 }}</td>
                            <td>{{ d.d2 }}</td>
                            <td>{{ d.d3 }}</td>
                            <td>{{ d.d4 }}</td>
                            <td>
                                <a href="{{ url_for('datatest.edit', id=d.id) }}">Edit</a>
                                <a href="{{ url_for('datatest.delete', id=d.id) }}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}